// Monster identity lives here so combat labels, unlock rules and the codex
// cannot drift apart. Chinese names follow the commonly used Undertale Wiki
// translations; gameplay descriptions are specific to this survivor game.

export const BASE_MONSTERS = [
  {
    key: "slime",
    type: "slime",
    name: "蛙吉特",
    english: "Froggit",
    region: "废墟",
    title: "会说呱语的引路者",
    lore: "废墟里最早遇见的怪物。性情温和，也常把地下世界的规则告诉迷路的人类。",
    skill: "稳步追近；数量多时会从四面压缩走位空间。",
    color: "#76d275",
  },
  {
    key: "bat",
    type: "bat",
    name: "忧郁虫虫",
    english: "Whimsun",
    region: "废墟",
    title: "连道歉都小声的飞虫",
    lore: "胆怯得几乎不敢战斗，总像下一秒就会哭着逃走。",
    skill: "高速蛇形飞行；血量低，但很容易穿过火力空隙。",
    color: "#c39ae0",
  },
  {
    key: "ghost",
    type: "ghost",
    name: "蔬菜兽",
    english: "Vegetoid",
    region: "废墟",
    title: "地下沙拉协会成员",
    lore: "执着地劝所有人多吃蔬菜。笑容热情，推销方式却有一点强硬。",
    skill: "缓慢压阵并承受更多伤害，常藏在快速怪物后方推进。",
    color: "#9fdc8f",
  },
  {
    key: "tank",
    type: "tank",
    name: "杰瑞",
    english: "Jerry",
    region: "雪镇",
    title: "谁也不想同行的家伙",
    lore: "总能把气氛变得尴尬。大家嘴上嫌弃它，最后却还是会等它跟上。",
    skill: "生命很高、移动缓慢、碰撞伤害重，是怪群中的肉盾。",
    color: "#e6c84e",
  },
  {
    key: "red",
    type: "red",
    name: "卢克眼",
    english: "Loox",
    region: "废墟",
    title: "讨厌被人找茬的独眼",
    lore: "名字和外形都在提醒你看着它，但它最讨厌别人欺负弱小。",
    skill: "登场后短暂免伤并双倍冲刺，必须避开第一轮突袭。",
    color: "#e05555",
  },
  {
    key: "orange",
    type: "orange",
    name: "疯狂魔术师",
    english: "Madjick",
    region: "核心",
    title: "自我陶醉的核心佣兵",
    lore: "戴着弯曲尖帽、操纵两颗魔法球，念咒时从不给别人插话的机会。",
    skill: "拥有三条命；每次复生会短暂无敌，环绕光球显示剩余命数。",
    color: "#f09a4a",
  },
  {
    key: "blue",
    type: "blue",
    name: "约刷亚",
    english: "Woshua",
    region: "瀑布",
    title: "洁癖过头的清洁狂",
    lore: "把清洁当成使命，恨不得连战场和对手一起洗得闪闪发亮。",
    skill: "攻击距离远于身体碰撞圈，浅蓝范围环就是危险边界。",
    color: "#5aa8e0",
  },
  {
    key: "purple",
    type: "purple",
    name: "冰帽盖",
    english: "Ice Cap",
    region: "雪镇",
    title: "只想让你夸帽子的少年",
    lore: "最珍惜头顶那顶冰帽。只要有人认真欣赏，它就会立刻神气起来。",
    skill: "标记玩家脚下，1 秒后瞬移突袭；紫色叉号会提前预警。",
    color: "#9a86e8",
  },
];

export const ELITE_MONSTERS = [
  {
    key: "elite_final_froggit",
    type: "slime",
    name: "终极蛙吉特",
    english: "Final Froggit",
    region: "困难模式 / 核心",
    title: "看透人生的蛙之贤者",
    lore: "蛙吉特的强大同族。原作中会在困难模式与核心现身，态度比外表更从容。",
    skill: "审判跃击：锁定脚下后跃迁重砸，绿色圆环收缩完毕时爆发。",
    color: "#7cf28a",
    minDifficulty: 1,
    debutTime: 90,
    unlock: "狂暴难度 1:30 后出现",
    skillId: "leap",
  },
  {
    key: "elite_whimsalot",
    type: "bat",
    name: "忧伤虫爵士",
    english: "Whimsalot",
    region: "困难模式 / 核心",
    title: "为荣誉而战的悲伤骑士",
    lore: "忧郁虫虫不再逃避后的姿态。仍然悲伤，却终于鼓起勇气正面战斗。",
    skill: "蝶翼冲锋：短暂蓄力后进入高速追击，沿途留下紫色残影。",
    color: "#d5a6ff",
    minDifficulty: 1,
    debutTime: 135,
    unlock: "狂暴难度 2:15 后出现",
    skillId: "rush",
  },
  {
    key: "elite_astigmatism",
    type: "red",
    name: "散光眼",
    english: "Astigmatism",
    region: "困难模式 / 核心",
    title: "要求你服从命令的凝视者",
    lore: "卢克眼更危险的同族。它在意的不是注视本身，而是你有没有照它说的做。",
    skill: "裁决凝视：红色视界扩张后，对范围内目标造成一次远程伤害。",
    color: "#ff6464",
    minDifficulty: 2,
    debutTime: 180,
    unlock: "地狱难度 3:00 后出现",
    skillId: "gaze",
  },
  {
    key: "elite_parsnik",
    type: "ghost",
    name: "欧防风兽",
    english: "Parsnik",
    region: "困难模式废墟",
    title: "甜言蜜语的根茎诱惑者",
    lore: "蔬菜兽在困难模式中的对应怪物，说话更甜，地下根须也更加危险。",
    skill: "根须盛宴：在玩家周围种下三枚橙色危险区，依次破土爆发。",
    color: "#ffb15d",
    minDifficulty: 2,
    debutTime: 225,
    unlock: "地狱难度 3:45 后出现",
    skillId: "roots",
  },
  {
    key: "elite_moldessa",
    type: "tank",
    name: "霉塑怪",
    english: "Moldessa",
    region: "困难模式废墟",
    title: "连自己的脸也认不清的硬质果冻",
    lore: "软泥怪在困难模式中的强大同族。脸总是拼错，却仍努力把五官摆回正确位置。",
    skill: "错位爆裂：在玩家周围排出五张错位面孔，预警结束后同时炸成八向碎片。",
    color: "#8fe38b",
    minDifficulty: 1,
    debutTime: 180,
    unlock: "狂暴难度 3:00 后出现",
    skillId: "faceBurst",
  },
  {
    key: "elite_migospel",
    type: "orange",
    name: "丑角福音虫",
    english: "Migospel",
    region: "困难模式废墟",
    title: "用笑声藏住忧虑的舞台虫",
    lore: "只要身边还有观众，它就把战斗演成滑稽秀；独处时，夸张笑脸才会短暂消失。",
    skill: "谢幕虫潮：虫群从左右幕布升起，只留下锁定位置中央的一条安全通道。",
    color: "#ff8fbf",
    minDifficulty: 1,
    debutTime: 225,
    unlock: "狂暴难度 3:45 后出现",
    skillId: "curtainRise",
  },
  {
    key: "elite_aaron",
    type: "blue",
    name: "亚伦",
    english: "Aaron",
    region: "瀑布",
    title: "把每次相遇都当成健美比赛的海马",
    lore: "肌肉、汗水和眨眼缺一不可。越有人回应挑战，它就会越用力地展示十二块腹肌。",
    skill: "肌肉压场：两侧巨臂逐渐合拢，汗滴同时锁定落下，必须及时回到中央空隙。",
    color: "#62d5d0",
    minDifficulty: 2,
    debutTime: 150,
    unlock: "地狱难度 2:30 后出现",
    skillId: "flexPressure",
  },
  {
    key: "elite_pyrope",
    type: "purple",
    name: "焰绳怪",
    english: "Pyrope",
    region: "热域",
    title: "永远嫌温度不够高的燃烧绳结",
    lore: "越热越开心，甚至把自己当成生日蛋糕上的蜡烛。橙色火焰要求对手迎面穿过去。",
    skill: "橙焰横扫：燃烧绳索横穿战场；火焰亮起时必须保持移动才能免受伤害。",
    color: "#ff8a3d",
    minDifficulty: 2,
    debutTime: 210,
    unlock: "地狱难度 3:30 后出现",
    skillId: "orangeRush",
  },
  {
    key: "elite_memoryhead",
    type: "ghost",
    name: "记忆头",
    english: "Memoryhead",
    region: "真实验室",
    title: "六张笑脸共享一段故障记忆",
    lore: "由六张面孔、骨头与脑状雾团组成的融合怪。它通过电话杂音说话，并邀请听见的人加入它们。",
    skill: "故障增殖：细小噪点在玩家周围生成，随后膨胀成五张扭曲笑脸并同时爆裂。",
    color: "#a8f0d0",
    minDifficulty: 2,
    debutTime: 225,
    unlock: "地狱 3:45 / 屠杀 3:15 后出现",
    skillId: "memoryFaces",
  },
  {
    key: "elite_reaper_bird",
    type: "bat",
    name: "死神鸟",
    english: "Reaper Bird",
    region: "真实验室",
    title: "三种怪物愿望重叠出的飞鸟",
    lore: "终极蛙吉特、忧伤虫爵士与散光眼的融合体。重叠话语里仍残留着勇气、祈祷与理解。",
    skill: "Everyman 蝶群：无头人影横穿战场，追踪头颅在预定位置聚拢，右侧留有撤离通道。",
    color: "#e8d8ff",
    minDifficulty: 3,
    debutTime: 270,
    unlock: "屠杀难度 4:00 后出现",
    skillId: "everymanFlock",
  },
];

export const ROUND_CHAMPIONS = [
  {
    key: "champion_greater_dog",
    championId: "greaterDog",
    baseType: "tank",
    type: "champion",
    name: "大犬汪",
    english: "Greater Dog",
    region: "雪镇",
    title: "把战斗当成游戏的皇家守卫犬",
    lore: "盔甲看起来威风凛凛，里面却是一只渴望玩耍和摸头的大狗。",
    skill: "蓝枪冲锋：锁定直线后猛冲；蓝色长枪只会伤害仍在移动的目标。",
    color: "#8fd6ff",
    unlock: "无尽审判第 1 轮首领",
    skillId: "dogCharge",
    hpFactor: 0.9,
    dmgFactor: 1,
  },
  {
    key: "champion_mad_dummy",
    championId: "madDummy",
    baseType: "ghost",
    type: "champion",
    name: "愤怒假人",
    english: "Mad Dummy",
    region: "瀑布垃圾场",
    title: "气到和假人身体融为一体的幽灵",
    lore: "普通攻击无法让它冷静。最好的办法，是让它召来的火力打回自己身上。",
    skill: "假人齐射：锁定玩家位置轰炸；把锁定圈引到首领脚下可以造成反伤。",
    color: "#ffd166",
    unlock: "无尽审判第 2 轮首领",
    skillId: "dummyVolley",
    hpFactor: 1.35,
    dmgFactor: 0.95,
  },
  {
    key: "champion_knight_knight",
    championId: "knightKnight",
    baseType: "tank",
    type: "champion",
    name: "骑士骑士",
    english: "Knight Knight",
    region: "核心",
    title: "在日月魔法中沉睡的重甲骑士",
    lore: "核心的佣兵战士。低声吟唱古老歌谣，让太阳与月亮替她作战。",
    skill: "月陨星落：连续标记五片区域，月光按标记顺序坠落爆炸。",
    color: "#c9b6ff",
    unlock: "无尽审判第 3 轮首领",
    skillId: "moonfall",
    hpFactor: 1.25,
    dmgFactor: 1.1,
  },
  {
    key: "champion_muffet",
    championId: "muffet",
    baseType: "red",
    type: "champion",
    name: "玛菲特",
    english: "Muffet",
    region: "热域",
    title: "为蜘蛛家族筹款的甜点老板",
    lore: "笑容甜美，蛛网和点心却一点也不温柔。她会把猎物固定在紫色丝线上。",
    skill: "蛛网宴席：铺开三条紫色轨道，其中一条亮起后会被蜘蛛群横扫。",
    color: "#d67cff",
    unlock: "无尽审判第 4 轮首领",
    skillId: "webFeast",
    hpFactor: 1.8,
    dmgFactor: 1.05,
  },
  {
    key: "champion_royal_guards",
    championId: "royalGuards",
    baseType: "tank",
    type: "champion",
    name: "皇家守卫 01&02",
    english: "Royal Guards",
    region: "热域",
    title: "并肩巡逻、绝不拆伙的双人小队",
    lore: "01 与 02 总把战斗叫作团队行动。黑色盔甲看似严肃，配合里却藏着说不出口的牵挂。",
    skill: "双向夹击：四条纵向剑路由上下同时推进，其中两条亮起并在交会时斩击。",
    color: "#ff9f6e",
    unlock: "无尽审判第 5 轮首领",
    skillId: "teamAttack",
    hpFactor: 2.05,
    dmgFactor: 1.12,
  },
  {
    key: "champion_mettaton_ex",
    championId: "mettatonEx",
    baseType: "red",
    type: "champion",
    name: "镁塔顿 EX",
    english: "Mettaton EX",
    region: "核心",
    title: "把生死决斗变成黄金时段的地下明星",
    lore: "真正的身体为聚光灯而生。对他而言，攻击、舞步与收视率从来都是同一场演出。",
    skill: "黄金舞台：九宫格聚光灯交替点亮，踩进亮起的危险格会遭到舞台爆破。",
    color: "#ff78b8",
    unlock: "无尽审判第 8 轮首领",
    skillId: "ratingStage",
    hpFactor: 2.35,
    dmgFactor: 1.15,
  },
  {
    key: "champion_glyde",
    championId: "glyde",
    baseType: "blue",
    type: "champion",
    name: "格莱德",
    english: "Glyde",
    region: "雪镇隐藏洞窟",
    title: "拒绝透露数值、只接受掌声的浮空明星",
    lore: "在神秘门外等待足够久才会现身。它自信得近乎傲慢，连自己的倒影都会令它嫉妒。",
    skill: "巨星爆场：三重星环轮流点亮危险带，中央巨星还会间歇反转近身安全区。",
    color: "#ffe36b",
    unlock: "无尽审判第 9 轮首领",
    skillId: "starBurst",
    hpFactor: 2.55,
    dmgFactor: 1.18,
  },
  {
    key: "champion_so_sorry",
    championId: "soSorry",
    baseType: "ghost",
    type: "champion",
    name: "抱歉怪",
    english: "So Sorry",
    region: "热域艺术俱乐部",
    title: "总在错误时间闯进战场的慌张画家",
    lore: "它并不想伤害任何人，只是尾巴、废纸和涂鸦总在最糟糕的时机失去控制。",
    skill: "蓝橙速写：蓝色尾击要求静止，橙色尾击要求移动，同时避开环形涂鸦爆点。",
    color: "#7fb7ff",
    unlock: "无尽审判第 10 轮首领",
    skillId: "tailSketch",
    hpFactor: 2.8,
    dmgFactor: 1.2,
  },
  {
    key: "champion_endogeny",
    championId: "endogeny",
    baseType: "tank",
    type: "champion",
    name: "犬神融合体",
    english: "Endogeny",
    region: "真实验室",
    title: "已经分不清由多少只狗组成的影子",
    lore: "数只雪镇犬类怪物融合后的形态。它仍渴望呼唤、玩耍和抚摸，只是兴奋时会沿墙疯狂冲刺。",
    skill: "火箭犬群：三条平行冲锋线轮流点亮，融合犬沿危险线高速贯穿并留下反向箭雨。",
    color: "#d8f3ff",
    unlock: "无尽审判第 6 轮首领",
    skillId: "rocketPack",
    hpFactor: 2.3,
    dmgFactor: 1.15,
  },
  {
    key: "champion_lemon_bread",
    championId: "lemonBread",
    baseType: "red",
    type: "champion",
    name: "柠檬面包",
    english: "Lemon Bread",
    region: "真实验室",
    title: "把整片战场变成特殊地狱的巨口",
    lore: "由害羞塞壬的姐姐、亚伦与模具怪等怪物融合而成。巨口闭合前，整片战场都会变成它的牙床。",
    skill: "巨齿牢笼：上下牙列同时咬合，只留下提前标出的单一横向安全带。",
    color: "#fff1a8",
    unlock: "无尽审判第 7 轮首领",
    skillId: "toothCage",
    hpFactor: 2.5,
    dmgFactor: 1.18,
  },
];

export const CODEX_MONSTERS = [...BASE_MONSTERS, ...ELITE_MONSTERS, ...ROUND_CHAMPIONS];
export const MONSTER_BY_TYPE = Object.fromEntries(BASE_MONSTERS.map((m) => [m.type, m]));

const ELITE_BY_KEY = Object.fromEntries(ELITE_MONSTERS.map((m) => [m.key, m]));
const ELITES_BY_TYPE = ELITE_MONSTERS.reduce((groups, monster) => {
  (groups[monster.type] ||= []).push(monster);
  return groups;
}, {});

export function eliteProfileFor(type, difficultyId, profileKey = null) {
  if (profileKey) {
    const selected = ELITE_BY_KEY[profileKey];
    return selected && selected.type === type && difficultyId >= selected.minDifficulty ? selected : null;
  }
  return (ELITES_BY_TYPE[type] || []).find((profile) => difficultyId >= profile.minDifficulty) || null;
}

export function eliteProfilePool(difficultyId, elapsed = Infinity) {
  const genocideLead = difficultyId >= 3 ? 30 : 0;
  const pool = ELITE_MONSTERS.filter(
    (m) => difficultyId >= m.minDifficulty && elapsed >= Math.max(60, m.debutTime - genocideLead)
  );
  return pool.length ? pool : null;
}

export function eliteTypePool(difficultyId, elapsed = Infinity) {
  return eliteProfilePool(difficultyId, elapsed)?.map((profile) => profile.type) || null;
}

export function codexKeyForEnemy(enemy) {
  return enemy.championProfile?.key || enemy.eliteProfile?.key || enemy.type;
}

export function championForRound(round) {
  const rotation = [0, 1, 2, 3, 4, 8, 9, 5, 6, 7];
  return ROUND_CHAMPIONS[rotation[(Math.max(1, round) - 1) % rotation.length]];
}
