const API = "https://api.sansgecao.com/v1";
export const leaderboardOnline = typeof location !== "undefined" && /(^|\.)sansgecao\.com$/.test(location.hostname || "");
let me = null, run = null, timer = null, result = "", rows = [], mode = "normal", character = "";
async function call(path, options={}) { const r=await fetch(API+path,{credentials:"include",...options,headers:{"content-type":"application/json",...(options.headers||{})}}); const data=await r.json(); if(!r.ok)throw new Error(data.error||"网络错误"); return data; }
export async function initLeaderboard(){if(!leaderboardOnline)return;try{me=(await call("/me")).player;}catch(e){result=e.message;}}
export function leaderboardProfile(){return me;}
export async function renameLeaderboard(){if(!leaderboardOnline)return;const name=prompt("输入新昵称（2-8字；改名后7天内不可再次修改）",me?.nickname||"");if(!name)return;try{me=(await call("/me/name",{method:"POST",body:JSON.stringify({nickname:name})})).player;result="改名成功";}catch(e){result=e.message;}}
export async function loadLeaderboard(nextMode=mode,nextChar=character){mode=nextMode;character=nextChar;try{rows=(await call(`/leaderboard?mode=${mode}${character?`&character=${character}`:""}`)).rows;result="";}catch(e){result=e.message;}}
export async function beginRankedRun(data,getStats){if(!leaderboardOnline||data.debug)return;try{run=await call("/runs",{method:"POST",body:JSON.stringify(data)});clearInterval(timer);timer=setInterval(()=>checkpointRankedRun(getStats),30000);}catch{run=null;}}
export async function checkpointRankedRun(getStats){if(!run)return;try{await call(`/runs/${run.runId}/checkpoint`,{method:"POST",body:JSON.stringify({...getStats(),token:run.token})});}catch{}}
export async function finishRankedRun(data){if(!run)return;clearInterval(timer);try{const x=await call(`/runs/${run.runId}/settle`,{method:"POST",body:JSON.stringify({...data,token:run.token})});result=`全球第 ${x.rank} 名 · ${x.score} 分`; }catch(e){result=e.message;}finally{run=null;}}
export function drawLeaderboard(ctx,w,h){ctx.save();ctx.fillStyle="#0a0810";ctx.fillRect(0,0,w,h);ctx.textAlign="center";ctx.fillStyle="#ffd166";ctx.font="bold 30px monospace";ctx.fillText("审 判 排 行 榜",w/2,48);ctx.fillStyle="#8fd6ff";ctx.font="14px monospace";ctx.fillText(`${me?.nickname||"游客加载中"} · 点击顶部昵称改名`,w/2,76);ctx.fillStyle="#c8c2d4";ctx.fillText(mode==="normal"?"普通榜：Boss 通关分（按分数）":"无尽榜：完成轮数优先，其次分数",w/2,105);ctx.textAlign="left";rows.slice(0,10).forEach((r,i)=>{ctx.fillStyle=i<3?"#ffd166":"#c8c2d4";ctx.fillText(`${String(i+1).padStart(2," ")}  ${r.nickname.padEnd(10,"　")} ${r.character.padEnd(6)} 难度${r.difficulty}  ${mode==="endless"?`${r.rounds}轮  `:""}${r.score}分`,170,145+i*34)});ctx.textAlign="center";ctx.fillStyle="#9a93ab";ctx.fillText(result||"点击左下切换榜单 · 右下返回",w/2,h-30);ctx.restore();}
export function leaderboardTap(x,y,w,h){if(y<95){renameLeaderboard();return "stay";}if(y>h-80&&x<w/2){loadLeaderboard(mode==="normal"?"endless":"normal");return "stay";}if(y>h-80&&x>w/2)return "back";return "stay";}
